[install]
# 7 days in seconds
minimumReleaseAge = 604800
# link workspace packages instead of installing from the registry
linkWorkspacePackages = true

[test]
preload = [
  "./packages/pulse/js/test/happydom.ts",
  "./packages/pulse/js/test/testing-library.ts",
]
